# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record,
# publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

variables:
  AZURE: True
  SARDES_OUTPUT_DIRNAME: 'sardes_1.0.0rc1_win_amd64'

pool:
  vmImage: 'windows-2019'

strategy:
  matrix:
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    python -m pip install wheel
    pip install -r requirements.txt
    pip install -r requirements-dev.txt
    pip install pytest-azurepipelines
  displayName: 'Install dependencies'

- script: |
    python runtests.py
  displayName: 'Run tests'
  continueOnError: false

- script: |
    codecov
  env:
    CODECOV_TOKEN: $(SECRET_CODECOV_TOKEN)
  displayName: 'Run codecov'

- script: |
    python -m pip install pyinstaller==4.9 tornado
    set PYTHONPATH=$(Build.SourcesDirectory);%PYTHONPATH%
    cd ./releases
    pyinstaller.exe sardes.spec
    cd ..
  displayName: 'Build package'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: '$(SARDES_OUTPUT_DIRNAME)'
    targetPath: '$(Build.SourcesDirectory)/releases/$(SARDES_OUTPUT_DIRNAME)'
